// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: financial_engine.proto

package financialenginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinancialEngine_CategorizeTransactions_FullMethodName       = "/ledgermeadow.financial_engine.v1.FinancialEngine/CategorizeTransactions"
	FinancialEngine_DetectRecurring_FullMethodName              = "/ledgermeadow.financial_engine.v1.FinancialEngine/DetectRecurring"
	FinancialEngine_EvaluateRules_FullMethodName                = "/ledgermeadow.financial_engine.v1.FinancialEngine/EvaluateRules"
	FinancialEngine_CalculateBudgetStatus_FullMethodName        = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateBudgetStatus"
	FinancialEngine_CalculateAvailableToSpend_FullMethodName    = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateAvailableToSpend"
	FinancialEngine_CalculateCashFlow_FullMethodName            = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateCashFlow"
	FinancialEngine_BuildProjection_FullMethodName              = "/ledgermeadow.financial_engine.v1.FinancialEngine/BuildProjection"
	FinancialEngine_CalculateGoal_FullMethodName                = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateGoal"
	FinancialEngine_CalculateLoanScenario_FullMethodName        = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateLoanScenario"
	FinancialEngine_CalculateHouseholdSettlement_FullMethodName = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateHouseholdSettlement"
	FinancialEngine_CalculateAnalyticsBreakdown_FullMethodName  = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateAnalyticsBreakdown"
	FinancialEngine_CalculateNetWorth_FullMethodName            = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateNetWorth"
	FinancialEngine_CalculateSubscriptionSummary_FullMethodName = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculateSubscriptionSummary"
	FinancialEngine_CalculatePlanningSummary_FullMethodName     = "/ledgermeadow.financial_engine.v1.FinancialEngine/CalculatePlanningSummary"
)

// FinancialEngineClient is the client API for FinancialEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinancialEngineClient interface {
	CategorizeTransactions(ctx context.Context, in *CategorizeTransactionsRequest, opts ...grpc.CallOption) (*CategorizeTransactionsResponse, error)
	DetectRecurring(ctx context.Context, in *DetectRecurringRequest, opts ...grpc.CallOption) (*DetectRecurringResponse, error)
	EvaluateRules(ctx context.Context, in *EvaluateRulesRequest, opts ...grpc.CallOption) (*EvaluateRulesResponse, error)
	CalculateBudgetStatus(ctx context.Context, in *CalculateBudgetStatusRequest, opts ...grpc.CallOption) (*CalculateBudgetStatusResponse, error)
	CalculateAvailableToSpend(ctx context.Context, in *CalculateAvailableToSpendRequest, opts ...grpc.CallOption) (*CalculateAvailableToSpendResponse, error)
	CalculateCashFlow(ctx context.Context, in *CalculateCashFlowRequest, opts ...grpc.CallOption) (*CalculateCashFlowResponse, error)
	BuildProjection(ctx context.Context, in *BuildProjectionRequest, opts ...grpc.CallOption) (*BuildProjectionResponse, error)
	CalculateGoal(ctx context.Context, in *CalculateGoalRequest, opts ...grpc.CallOption) (*CalculateGoalResponse, error)
	CalculateLoanScenario(ctx context.Context, in *CalculateLoanScenarioRequest, opts ...grpc.CallOption) (*CalculateLoanScenarioResponse, error)
	CalculateHouseholdSettlement(ctx context.Context, in *CalculateHouseholdSettlementRequest, opts ...grpc.CallOption) (*CalculateHouseholdSettlementResponse, error)
	CalculateAnalyticsBreakdown(ctx context.Context, in *CalculateAnalyticsBreakdownRequest, opts ...grpc.CallOption) (*CalculateAnalyticsBreakdownResponse, error)
	CalculateNetWorth(ctx context.Context, in *CalculateNetWorthRequest, opts ...grpc.CallOption) (*CalculateNetWorthResponse, error)
	CalculateSubscriptionSummary(ctx context.Context, in *CalculateSubscriptionSummaryRequest, opts ...grpc.CallOption) (*CalculateSubscriptionSummaryResponse, error)
	CalculatePlanningSummary(ctx context.Context, in *CalculatePlanningSummaryRequest, opts ...grpc.CallOption) (*CalculatePlanningSummaryResponse, error)
}

type financialEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialEngineClient(cc grpc.ClientConnInterface) FinancialEngineClient {
	return &financialEngineClient{cc}
}

func (c *financialEngineClient) CategorizeTransactions(ctx context.Context, in *CategorizeTransactionsRequest, opts ...grpc.CallOption) (*CategorizeTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategorizeTransactionsResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CategorizeTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) DetectRecurring(ctx context.Context, in *DetectRecurringRequest, opts ...grpc.CallOption) (*DetectRecurringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectRecurringResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_DetectRecurring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) EvaluateRules(ctx context.Context, in *EvaluateRulesRequest, opts ...grpc.CallOption) (*EvaluateRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateRulesResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_EvaluateRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateBudgetStatus(ctx context.Context, in *CalculateBudgetStatusRequest, opts ...grpc.CallOption) (*CalculateBudgetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateBudgetStatusResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateBudgetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateAvailableToSpend(ctx context.Context, in *CalculateAvailableToSpendRequest, opts ...grpc.CallOption) (*CalculateAvailableToSpendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateAvailableToSpendResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateAvailableToSpend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateCashFlow(ctx context.Context, in *CalculateCashFlowRequest, opts ...grpc.CallOption) (*CalculateCashFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateCashFlowResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateCashFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) BuildProjection(ctx context.Context, in *BuildProjectionRequest, opts ...grpc.CallOption) (*BuildProjectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildProjectionResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_BuildProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateGoal(ctx context.Context, in *CalculateGoalRequest, opts ...grpc.CallOption) (*CalculateGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateGoalResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateLoanScenario(ctx context.Context, in *CalculateLoanScenarioRequest, opts ...grpc.CallOption) (*CalculateLoanScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateLoanScenarioResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateLoanScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateHouseholdSettlement(ctx context.Context, in *CalculateHouseholdSettlementRequest, opts ...grpc.CallOption) (*CalculateHouseholdSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateHouseholdSettlementResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateHouseholdSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateAnalyticsBreakdown(ctx context.Context, in *CalculateAnalyticsBreakdownRequest, opts ...grpc.CallOption) (*CalculateAnalyticsBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateAnalyticsBreakdownResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateAnalyticsBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateNetWorth(ctx context.Context, in *CalculateNetWorthRequest, opts ...grpc.CallOption) (*CalculateNetWorthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateNetWorthResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateNetWorth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculateSubscriptionSummary(ctx context.Context, in *CalculateSubscriptionSummaryRequest, opts ...grpc.CallOption) (*CalculateSubscriptionSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateSubscriptionSummaryResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculateSubscriptionSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialEngineClient) CalculatePlanningSummary(ctx context.Context, in *CalculatePlanningSummaryRequest, opts ...grpc.CallOption) (*CalculatePlanningSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePlanningSummaryResponse)
	err := c.cc.Invoke(ctx, FinancialEngine_CalculatePlanningSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialEngineServer is the server API for FinancialEngine service.
// All implementations must embed UnimplementedFinancialEngineServer
// for forward compatibility.
type FinancialEngineServer interface {
	CategorizeTransactions(context.Context, *CategorizeTransactionsRequest) (*CategorizeTransactionsResponse, error)
	DetectRecurring(context.Context, *DetectRecurringRequest) (*DetectRecurringResponse, error)
	EvaluateRules(context.Context, *EvaluateRulesRequest) (*EvaluateRulesResponse, error)
	CalculateBudgetStatus(context.Context, *CalculateBudgetStatusRequest) (*CalculateBudgetStatusResponse, error)
	CalculateAvailableToSpend(context.Context, *CalculateAvailableToSpendRequest) (*CalculateAvailableToSpendResponse, error)
	CalculateCashFlow(context.Context, *CalculateCashFlowRequest) (*CalculateCashFlowResponse, error)
	BuildProjection(context.Context, *BuildProjectionRequest) (*BuildProjectionResponse, error)
	CalculateGoal(context.Context, *CalculateGoalRequest) (*CalculateGoalResponse, error)
	CalculateLoanScenario(context.Context, *CalculateLoanScenarioRequest) (*CalculateLoanScenarioResponse, error)
	CalculateHouseholdSettlement(context.Context, *CalculateHouseholdSettlementRequest) (*CalculateHouseholdSettlementResponse, error)
	CalculateAnalyticsBreakdown(context.Context, *CalculateAnalyticsBreakdownRequest) (*CalculateAnalyticsBreakdownResponse, error)
	CalculateNetWorth(context.Context, *CalculateNetWorthRequest) (*CalculateNetWorthResponse, error)
	CalculateSubscriptionSummary(context.Context, *CalculateSubscriptionSummaryRequest) (*CalculateSubscriptionSummaryResponse, error)
	CalculatePlanningSummary(context.Context, *CalculatePlanningSummaryRequest) (*CalculatePlanningSummaryResponse, error)
	mustEmbedUnimplementedFinancialEngineServer()
}

// UnimplementedFinancialEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialEngineServer struct{}

func (UnimplementedFinancialEngineServer) CategorizeTransactions(context.Context, *CategorizeTransactionsRequest) (*CategorizeTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CategorizeTransactions not implemented")
}
func (UnimplementedFinancialEngineServer) DetectRecurring(context.Context, *DetectRecurringRequest) (*DetectRecurringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectRecurring not implemented")
}
func (UnimplementedFinancialEngineServer) EvaluateRules(context.Context, *EvaluateRulesRequest) (*EvaluateRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateRules not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateBudgetStatus(context.Context, *CalculateBudgetStatusRequest) (*CalculateBudgetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBudgetStatus not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateAvailableToSpend(context.Context, *CalculateAvailableToSpendRequest) (*CalculateAvailableToSpendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateAvailableToSpend not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateCashFlow(context.Context, *CalculateCashFlowRequest) (*CalculateCashFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateCashFlow not implemented")
}
func (UnimplementedFinancialEngineServer) BuildProjection(context.Context, *BuildProjectionRequest) (*BuildProjectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildProjection not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateGoal(context.Context, *CalculateGoalRequest) (*CalculateGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateGoal not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateLoanScenario(context.Context, *CalculateLoanScenarioRequest) (*CalculateLoanScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateLoanScenario not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateHouseholdSettlement(context.Context, *CalculateHouseholdSettlementRequest) (*CalculateHouseholdSettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateHouseholdSettlement not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateAnalyticsBreakdown(context.Context, *CalculateAnalyticsBreakdownRequest) (*CalculateAnalyticsBreakdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateAnalyticsBreakdown not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateNetWorth(context.Context, *CalculateNetWorthRequest) (*CalculateNetWorthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateNetWorth not implemented")
}
func (UnimplementedFinancialEngineServer) CalculateSubscriptionSummary(context.Context, *CalculateSubscriptionSummaryRequest) (*CalculateSubscriptionSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateSubscriptionSummary not implemented")
}
func (UnimplementedFinancialEngineServer) CalculatePlanningSummary(context.Context, *CalculatePlanningSummaryRequest) (*CalculatePlanningSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePlanningSummary not implemented")
}
func (UnimplementedFinancialEngineServer) mustEmbedUnimplementedFinancialEngineServer() {}
func (UnimplementedFinancialEngineServer) testEmbeddedByValue()                         {}

// UnsafeFinancialEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialEngineServer will
// result in compilation errors.
type UnsafeFinancialEngineServer interface {
	mustEmbedUnimplementedFinancialEngineServer()
}

func RegisterFinancialEngineServer(s grpc.ServiceRegistrar, srv FinancialEngineServer) {
	// If the following call panics, it indicates UnimplementedFinancialEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialEngine_ServiceDesc, srv)
}

func _FinancialEngine_CategorizeTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategorizeTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CategorizeTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CategorizeTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CategorizeTransactions(ctx, req.(*CategorizeTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_DetectRecurring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRecurringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).DetectRecurring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_DetectRecurring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).DetectRecurring(ctx, req.(*DetectRecurringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_EvaluateRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).EvaluateRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_EvaluateRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).EvaluateRules(ctx, req.(*EvaluateRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateBudgetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateBudgetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateBudgetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateBudgetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateBudgetStatus(ctx, req.(*CalculateBudgetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateAvailableToSpend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAvailableToSpendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateAvailableToSpend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateAvailableToSpend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateAvailableToSpend(ctx, req.(*CalculateAvailableToSpendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateCashFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateCashFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateCashFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateCashFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateCashFlow(ctx, req.(*CalculateCashFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_BuildProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildProjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).BuildProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_BuildProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).BuildProjection(ctx, req.(*BuildProjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateGoal(ctx, req.(*CalculateGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateLoanScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateLoanScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateLoanScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateLoanScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateLoanScenario(ctx, req.(*CalculateLoanScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateHouseholdSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateHouseholdSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateHouseholdSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateHouseholdSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateHouseholdSettlement(ctx, req.(*CalculateHouseholdSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateAnalyticsBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAnalyticsBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateAnalyticsBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateAnalyticsBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateAnalyticsBreakdown(ctx, req.(*CalculateAnalyticsBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateNetWorth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateNetWorthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateNetWorth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateNetWorth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateNetWorth(ctx, req.(*CalculateNetWorthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculateSubscriptionSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateSubscriptionSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculateSubscriptionSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculateSubscriptionSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculateSubscriptionSummary(ctx, req.(*CalculateSubscriptionSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialEngine_CalculatePlanningSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePlanningSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialEngineServer).CalculatePlanningSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialEngine_CalculatePlanningSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialEngineServer).CalculatePlanningSummary(ctx, req.(*CalculatePlanningSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialEngine_ServiceDesc is the grpc.ServiceDesc for FinancialEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledgermeadow.financial_engine.v1.FinancialEngine",
	HandlerType: (*FinancialEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CategorizeTransactions",
			Handler:    _FinancialEngine_CategorizeTransactions_Handler,
		},
		{
			MethodName: "DetectRecurring",
			Handler:    _FinancialEngine_DetectRecurring_Handler,
		},
		{
			MethodName: "EvaluateRules",
			Handler:    _FinancialEngine_EvaluateRules_Handler,
		},
		{
			MethodName: "CalculateBudgetStatus",
			Handler:    _FinancialEngine_CalculateBudgetStatus_Handler,
		},
		{
			MethodName: "CalculateAvailableToSpend",
			Handler:    _FinancialEngine_CalculateAvailableToSpend_Handler,
		},
		{
			MethodName: "CalculateCashFlow",
			Handler:    _FinancialEngine_CalculateCashFlow_Handler,
		},
		{
			MethodName: "BuildProjection",
			Handler:    _FinancialEngine_BuildProjection_Handler,
		},
		{
			MethodName: "CalculateGoal",
			Handler:    _FinancialEngine_CalculateGoal_Handler,
		},
		{
			MethodName: "CalculateLoanScenario",
			Handler:    _FinancialEngine_CalculateLoanScenario_Handler,
		},
		{
			MethodName: "CalculateHouseholdSettlement",
			Handler:    _FinancialEngine_CalculateHouseholdSettlement_Handler,
		},
		{
			MethodName: "CalculateAnalyticsBreakdown",
			Handler:    _FinancialEngine_CalculateAnalyticsBreakdown_Handler,
		},
		{
			MethodName: "CalculateNetWorth",
			Handler:    _FinancialEngine_CalculateNetWorth_Handler,
		},
		{
			MethodName: "CalculateSubscriptionSummary",
			Handler:    _FinancialEngine_CalculateSubscriptionSummary_Handler,
		},
		{
			MethodName: "CalculatePlanningSummary",
			Handler:    _FinancialEngine_CalculatePlanningSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "financial_engine.proto",
}
